language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to run tests
script:
  - coverage run --source trex -m py.test
before_install:
  - pip install -r requirements-dev.txt
  - pip install codecov
after_success:
  - codecov
branches:
  only:
    - master