name: test trrex package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: install dependencies and project
      run: |
        uv sync --all-extras --all-groups
      working-directory: ${{ github.workspace }}

    - name: test with coverage
      run: uv run coverage run --source trrex -m pytest

    - name: publish coverage
      run: codecov
